Feat/dao 747 Write methods for getting NFT details used in table/card view
RootstockCollective/dao-backend-services pull request #16
Opened 2024-10-18 14:05 UTC by LordCheta

2024-10-21 15:45 UTC, sleyter93 requested changes
Review the comments, and also, we need to include documentation for this new endpoint, you should add into `src/api/openapi.js`

2024-10-21 15:45 UTC, sleyter93 commented on .env.dao
We should not delete this file.

2024-10-21 15:45 UTC, sleyter93 commented on src/index.ts
We should not delete this file.

2024-10-21 15:45 UTC, sleyter93 commented on src/blockscoutApi/index.ts
> +    console.log('getting nft holders data')
Do you think this message is essential?

2024-10-21 15:45 UTC, sleyter93 commented on src/blockscoutApi/index.ts
> +        const transformedResponse = nftHolderTransformedData(response.data.items)
Maybe we could rename this; another option could be mapToNftHolder
```suggestion
        const nftHolders = transformResponseToNftHolder(response.data.items)
```

2024-10-21 15:45 UTC, sleyter93 commented on src/blockscoutApi/types.ts
> +export interface NftTokenHolderOwner {
We should reuse the Account interface, according to Blockscout docs, is reusing that interface.

2024-10-21 15:50 UTC, LordCheta commented on .env.dao
Oh yes, I only removed from my commit, I made a change there only for my local development

2024-10-21 15:50 UTC, LordCheta commented on src/index.ts
This too

2024-10-22 06:27 UTC, sleyter93 approved these changes

2024-10-22 06:27 UTC, merged