Update SECURITY.md
RootstockCollective/dao-backend-services pull request #6
Opened 2024-09-14 09:21 UTC by jessgusclark

Updating security document at the request of @bcodesido to match the other Collective Security disclosures.

2024-09-16 16:06 UTC, bcodesido requested changes

2024-09-16 16:06 UTC, bcodesido commented on SECURITY.md
> +For all security related issues, use the GitHub Security Advisory ["Report a Vulnerability"](https://github.com/RootstockCollective/dao-frontend/security/advisories/new) tab.
repo name is wrong

2024-09-16 16:06 UTC, bcodesido commented on SECURITY.md
> +**Ensure the bug was not already reported** by searching on GitHub under [Issues](https://github.com/RootstockCollective/dao-frontend/issues).
same as above

2024-09-19 17:36 UTC, sleyter93 commented on SECURITY.md
> +For all security related issues, use the GitHub Security Advisory ["Report a Vulnerability"](https://github.com/RootstockCollective/dao-frontend/security/advisories/new) tab.
The repo name is updated

2024-09-19 17:37 UTC, sleyter93 commented on SECURITY.md
> +**Ensure the bug was not already reported** by searching on GitHub under [Issues](https://github.com/RootstockCollective/dao-frontend/issues).
The repo name is updated

2024-09-23 14:54 UTC, bcodesido approved these changes

2024-09-25 13:00 UTC, merged